language: python
# Generate this env list with:
# tox -l | awk '{ print "  - TOX_ENV="$0}'
env:
  - TOX_ENV=django15-py26
  - TOX_ENV=django15-py27
  - TOX_ENV=django16-py26
  - TOX_ENV=django16-py27
  - TOX_ENV=django16-py33
  - TOX_ENV=django17-py27
  - TOX_ENV=django17-py33
  - TOX_ENV=django17-py34
  - TOX_ENV=django18-py27
  - TOX_ENV=django18-py34
  - TOX_ENV=django19-py27
  - TOX_ENV=django19-py34
  - TOX_ENV=django40-py38
  - TOX_ENV=django40-py39
  - TOX_ENV=django40-py310
  - TOX_ENV=django40-py311
  - TOX_ENV=coveralls-django40-py311
install: pip install tox coveralls
script: tox -e $TOX_ENV
after_success: coveralls
sudo: false
